"""add menu_items orders order_items

Revision ID: f90c5aa9fdab
Revises: e4c7fc443ae4
Create Date: 2026-03-13 16:46:22.541803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90c5aa9fdab'
down_revision: Union[str, Sequence[str], None] = 'e4c7fc443ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
